### ISSUE TITLE
Prevent error if there is no milestone in the Jira project to import

### ISSUE THREAD

**Issue by lemeurherve** [lemeurherve/jira-issues-importer#2]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/91831478/158582519-c2dd77a6-6c50-42ec-892a-596c0e1b2cd7.png">

**Comment by lemeurherve** [comment]
@timja this is fixed in your PR #3 isn't it?

**Comment by timja** [comment]
Not intentionally but I definitely didn't see this error.
